fix: bring os_js.go up to date with os.go
Recent changes to os_js.go added WithBoundOS and ChrootOSFS.

These changes were not propagated to os_js.go, which results in
the following build failures in go-git:

% GOOS=js GOARCH=wasm gb ./...
github.com/go-git/go-git/v6
./remote.go:214:32: undefined: osfs.WithBoundOS
./repository.go:348:29: undefined: osfs.WithBoundOS
./repository.go:353:28: undefined: osfs.WithBoundOS
./repository.go:460:28: undefined: osfs.WithBoundOS
./repository.go:468:44: undefined: osfs.WithBoundOS
./repository.go:528:32: undefined: osfs.WithBoundOS
./repository.go:531:46: undefined: osfs.WithBoundOS
./repository.go:551:36: undefined: osfs.WithBoundOS
./repository.go:553:62: undefined: osfs.WithBoundOS

This commit brings os_js.go up to date with os.go to fix this.

All tests pass with GOOS=js GOARCH=wasm now.

Signed-off-by: Christian Stewart <christian@aperture.us>